# Documentation Swagger UI
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: 
        _controller: nelmio_api_doc.controller.swagger_ui

# JSON OpenAPI
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: 
        _controller: nelmio_api_doc.controller.swagger